<a href="https://colab.research.google.com/github/JuliaKoryukova/Machine-Learning/blob/main/01_Work_with_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Работа с библиотекой Pandas

1. Загрузка набора данных из файла **car_data.csv**

In [ ]:
import pandas as pd
!gdown 1kfwKDsUs9I3jaYxLQhbz8ofEIEHSGPBT
df = pd.read_csv('https://drive.google.com/uc?id=1kfwKDsUs9I3jaYxLQhbz8ofEIEHSGPBT')

Downloading...
From: https://drive.google.com/uc?id=1kfwKDsUs9I3jaYxLQhbz8ofEIEHSGPBT
To: /content/car_data.csv
100% 816k/816k [00:00<00:00, 76.9MB/s]

2. Анализ пропусков в данных. Удаление строк или столбцов, содержащих пропуски.

In [ ]:
df = df.rename(columns={'Unnamed: 0': 'Unnamed:_0', 'Car_id': 'Car_id', 'Date': 'Date','Customer Name': 'Customer_Name', 'Gender': 'Gender',
       'Annual Income': 'Annual_Income', 'Dealer_Name': 'Dealer_Name', 'Company': 'Company', 'Model': 'Model', 'Engine': 'Engine',
       'Transmission': 'Transmission', 'Color': 'Color', 'Price ($)': 'Price_($)', 'Dealer_No ': 'Dealer_No', 'Body Style': 'Body_Style',
       'Phone': 'Phone', 'Dealer_Region': 'Dealer_Region'})
df.isnull().sum()
df.dropna(inplace=True)

3. Вычисление среднего дохода клиентов, купивших автомобиль марки Toyota Camry.

In [ ]:
camry_model = df[(df['Company'] == 'Toyota') & (df['Model'] == 'Camry')]

average_clients_income = camry_model['Annual_Income'].mean()
average_clients_income

776609.375

4. Топ 10 самых дорогих марок автомобилей за представленный период времени.

In [ ]:
avg_prices = df.groupby('Company')['Price_($)'].mean().sort_values(ascending=False).head(10)
avg_prices

Company
Cadillac      41124.325203
Saab          40941.048780
Lincoln       32987.953271
Lexus         32930.897436
Buick         31560.687500
Oldsmobile    31387.188034
Plymouth      30604.331169
Saturn        30531.367188
Toyota        30415.163717
Pontiac       29635.026738
Name: Price_($), dtype: float64

5. Средняя стоимость автомобилей по типам кузова (Body Style), используя метод groupby.

In [ ]:
average_cost_body_style = df.groupby('Body_Style')['Price_($)'].mean().sort_values(ascending=False)
average_cost_body_style

Body_Style
Passenger    29845.254130
Sedan        29698.673056
Hardtop      29575.564677
Hatchback    27377.561126
SUV          26729.765799
Name: Price_($), dtype: float64

6. Автомобили, которые приобрели 10 клиентов с самым высоким доходом

In [ ]:
top_10_clients = df.sort_values('Annual_Income', ascending=False).head(10)
top_10_clients[['Customer_Name', 'Annual_Income', 'Company', 'Model']]

     Customer_Name  Annual_Income     Company           Model
4755        Yaakov        6240000    Chrysler        Concorde
1227        Athena        5800000    Cadillac        Eldorado
1233     Francesca        5770000       Volvo             C70
3329         Fatou        5600000      Nissan      Pathfinder
2101         Malka        5525000       Volvo             S40
2801          Mila        5510000   Chevrolet        Corvette
2452         Judah        5300000     Porsche  Carrera Cabrio
2973         Emily        5110000  Volkswagen             GTI
3129          Aria        4900000         BMW            528i
3907        Jazmin        4802500        Ford          Ranger

7. Автомобили, которые приобрели 10 клиентов с самым низким доходом

In [ ]:
low_10_clients = df.sort_values('Annual_Income', ascending=True).head(10)
low_10_clients[['Customer_Name', 'Annual_Income', 'Company', 'Model']]

     Customer_Name  Annual_Income     Company       Model
0        Geraldine          13500        Ford  Expedition
1709        Nathan          13500         BMW        323i
1707          Musa          13500         BMW        528i
3959         Alana          13500       Dodge     Stratus
1701       Michael          13500  Volkswagen         GTI
1699           Max          13500       Volvo         S80
1695         Golda          13500       Lexus       LS400
3965         Miley          13500  Volkswagen      Cabrio
3967        Miriam          13500        Ford    Explorer
3968     Stephanie          13500     Hyundai      Accent

8. Создание нового столбца, значения которого равны логарифму от величины дохода клиентов.

In [ ]:
import numpy as np
df['Log_Annual_Income'] = np.log(df['Annual_Income'])
df.head()

,Unnamed:_0,Car_id,Date,Customer_Name,Gender,Annual_Income,Dealer_Name,Company,Model,Engine,Transmission,Color,Price_($),Dealer_No,Body_Style,Phone,Dealer_Region,Log_Annual_Income
0,0,C_CND_000001,1/2/2022,Geraldine,Male,13500,Buddy Storbeck's Diesel Service Inc,Ford,Expedition,DoubleÂ Overhead Camshaft,Auto,Black,26000,06457-3834,SUV,8264678,Middletown,9.510445
1,1,C_CND_000002,1/2/2022,Gia,Male,1480000,C & M Motors Inc,Dodge,Durango,DoubleÂ Overhead Camshaft,Auto,Black,19000,60504-7114,SUV,6848189,Aurora,14.207553
2,2,C_CND_000003,1/2/2022,Gianna,Male,1035000,Capitol KIA,Cadillac,Eldorado,Overhead Camshaft,Manual,Red,31500,38701-8047,Passenger,7298798,Greenville,13.849912
3,3,C_CND_000004,1/2/2022,Giselle,Male,13500,Chrysler of Tri-Cities,Toyota,Celica,Overhead Camshaft,Manual,Pale White,14000,99301-3882,SUV,6257557,Pasco,9.510445
4,4,C_CND_000005,1/2/2022,Grace,Male,1465000,Chrysler Plymouth,Acura,TL,DoubleÂ Overhead Camshaft,Auto,Red,24500,53546-9427,Hatchback,7081483,Janesville,14.197366